# Generated by Django 5.0.6 on 2024-07-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartitem_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
